name: StorageVolumes
authors: [codist]
description: An addon to Slimefun based on the mod Storage Drawers by jaquadro.
website: https://github.com/ImCodist/storage-volumes

main: xyz.imcodist.slimefunaddon.StorageVolumes

version: ${project.version}
api-version: 1.14

depend:
- Slimefun